### ISSUE TITLE
Is this open for adoption?

### ISSUE THREAD

**Issue by ambs** [rjbs/tapsimple#13]

**Comment by rjbs** [comment]
Why do you ask?

**Comment by ambs** [comment]
Because it is not available to install from PIP (it looks like)...

**Comment by rjbs** [comment]
Are you using this library?  Does it have benefits over pycotap or other on-PIP ones?

**Comment by ambs** [comment]
It looks easier to use for Beginners.
I want to put my students working on some tests, and it seems more straightforward.
But it can be my Perl twisted mind :-)

Alberto Simões

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by saboredge** [comment]
Agreed with @ambs, and also, tapsimple enables concise code so you don't have to build tests for your tests :) Well done, @rjbs, I would also like to use this code for students.

**Comment by rjbs** [comment]
It's not really released anywhere but github, so I don't own any namespace on it, and the license is MIT.  Feel free to release it wherever you like, in line with the terms of its license.
