### ISSUE TITLE
The "PyTAP" name clashes with other projects 

### ISSUE THREAD

**Issue by shlomif** [rjbs/tapsimple#9]
The "PyTAP" name clashes with other projects , see: https://duckduckgo.com/?q=pytap&ia=about , namely there are also:

* https://pypi.python.org/pypi/PyTap/

* http://www.findbestopensource.com/product/pytap

* http://123pyt.org/school-of-performing-arts/dance/dance-companies-2/pytap-co/

And possibly others. It would be a good idea to publish what is now called "PyTAP" on PyPI under a unique and unambiguous identifier so it could be used without the need to be embedded. Also see http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822672 .

Thanks! -- @shlomif

**Comment by rjbs** [comment]
You included, in your list, the tap dance classes for children that are held in my home town.  Was this a joke?

**Comment by rjbs** [comment]
I have renamed things to tapsimple and registered this with pypi.

**Comment by shlomif** [comment]
@rjbs : thanks for the renaming! Much appreciated. Right now, a version 0.001/etc. release on PyPI would be appreciated so: 1. it will be possible to package it as RPMs/DEBs/etc. 2. one won't have to embed the code directly inside a VCS repository and have pep8/flake8 complain about it.
